module ddsbench
{
    struct Latency
    {
        long filter; // Field that can be used for filter
        sequence<octet> payload;
    };
    #pragma keylist Latency

    struct Throughput
    {
        long id;
        long filter; // Field that can be used for filter
        unsigned long long count;
        sequence<octet> payload;
    };
    #pragma keylist Throughput id
};
